# Generated by Django 5.2.15 on 2026-07-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiCenterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'ski_center_profile',
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('aktivna', 'Aktivna'), ('neaktivna', 'Neaktivna')], default='aktivna', max_length=10)),
                ('ski_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='ski_center.skicenterprofile')),
            ],
            options={
                'db_table': 'lift',
            },
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('difficulty', models.CharField(choices=[('plava', 'Plava'), ('crvena', 'Crvena'), ('cena', 'Crna')], max_length=10)),
                ('status', models.CharField(choices=[('otvorena', 'Otvorena'), ('zatvorena', 'Zatvorena')], default='otvorena', max_length=10)),
                ('ski_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slopes', to='ski_center.skicenterprofile')),
            ],
            options={
                'db_table': 'slope',
            },
        ),
    ]
