# Generated by Django 6.0.6 on 2026-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skicenterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ski_center_photos/'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skicenterprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slope',
            name='difficulty',
            field=models.CharField(choices=[('plava', 'Plava'), ('crvena', 'Crvena'), ('crna', 'Crna')], max_length=10),
        ),
        migrations.AlterField(
            model_name='slope',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
