# Generated by Django 6.0.6 on 2026-07-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_center', '0003_alter_lift_id_alter_skicenterprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skicenterprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='skicenterprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
