# Generated by Django 5.2.15 on 2026-07-10 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('ski_center', 'Ski centar'), ('rental', 'Rental firma'), ('ski_skola', 'Ski škola'), ('instructor', 'Instruktor')], max_length=20)),
                ('business_name', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profile',
            },
        ),
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('ski_center', 'Ski centar'), ('rental', 'Rental firma'), ('ski_skola', 'Ski škola'), ('instructor', 'Instruktor')], max_length=20)),
                ('business_name', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('na_cekanju', 'Na čekanju'), ('odobreno', 'Odobreno'), ('odbijeno', 'Odbijeno')], default='na_cekanju', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_request',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('profilePhotoUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_profile',
            },
        ),
    ]
