# Generated by Django 5.2.15 on 2026-07-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
