# Generated by Django 5.2.15 on 2026-07-14 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_businessrequest_reject_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('odobri_zahtev', 'Odobrio zahtev'), ('odbij_zahtev', 'Odbio zahtev'), ('ukloni_recenziju', 'Uklonio recenziju'), ('blokiraj', 'Blokirao nalog')], max_length=30)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
