# Generated by Django 5.2.15 on 2026-07-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ski_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('freeride', 'Freeride'), ('pocetnici', 'Početnička nastava'), ('snowboard', 'Snowboard'), ('napredna', 'Napredna tehnika')], max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprofile')),
                ('ski_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ski_center.skicenterprofile')),
            ],
            options={
                'db_table': 'instructor_profile',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='instructor.instructorprofile')),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ceka_potvrdu', 'Čeka potvrdu'), ('potvrdjena', 'Potvrđena'), ('realizovana', 'Realizovana'), ('otkazana', 'Otkazana')], default='ceka_potvrdu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.clientprofile')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructor.timeslot')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
