# Generated by Django 5.2.15 on 2026-07-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ceka_potvrdu', 'Čeka potvrdu'), ('potvrdjena', 'Potvrđena'), ('realizovana', 'Realizovana'), ('otkazana', 'Otkazana'), ('odbijena', 'Odbijena')], default='ceka_potvrdu', max_length=20),
        ),
    ]
