# Generated by Django 5.2.15 on 2026-07-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_businessprofile_id_alter_businessrequest_id_and_more'),
        ('ski_center', '0003_alter_lift_id_alter_skicenterprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiSchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprofile')),
                ('ski_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ski_schools', to='ski_center.skicenterprofile')),
            ],
            options={
                'db_table': 'ski_school_profile',
            },
        ),
    ]
